"""Deterministic, template-based rendering of a HypothesisSet to Markdown.

No LLM, no free-form generation — pure string templating over the validated
structure. This is the kind of rendering that will later populate the inspector.
"""

from __future__ import annotations

from .schema import HypothesisSet, SourceHypothesis

_TIER_LABEL = {
    "high": "HIGH",
    "moderate": "MODERATE",
    "low": "LOW",
    "insufficient": "INSUFFICIENT",
}


def _hypothesis_md(h: SourceHypothesis) -> str:
    lines: list[str] = []
    lines.append(f"### {h.id} (rank {h.rank}) — {h.candidate.descriptor}")
    lines.append("")
    lines.append(
        f"**Confidence: {_TIER_LABEL[h.confidence_tier.value]}** · "
        f"heuristic score {h.score:.2f} *(documented heuristic, not a probability)*"
    )
    lines.append("")
    lines.append(f"_{h.confidence_rationale}_")
    lines.append("")
    lines.append(f"**Claim.** {h.claim}")
    lines.append("")
    if h.candidate.ogim_id is not None:
        lines.append(
            f"**Candidate (OGIM-traceable).** {h.candidate.ogim_name} "
            f"(OGIM_ID {h.candidate.ogim_id}, layer `{h.candidate.ogim_layer}`)."
        )
    else:
        lines.append(
            f"**Candidate.** Sector-level: {h.candidate.descriptor} "
            f"(no OGIM point record — stated for completeness)."
        )
    lines.append("")
    lines.append("**Score components** (weighted; shown for transparency):")
    lines.append("")
    lines.append("| component | value | weight | contribution | rationale |")
    lines.append("|---|---:|---:|---:|---|")
    for c in h.score_components:
        lines.append(
            f"| {c.name} | {c.value:.2f} | {c.weight:.2f} | {c.contribution:.3f} | {c.rationale} |"
        )
    lines.append(f"| **score** | | | **{h.score:.2f}** | weighted sum |")
    lines.append("")
    lines.append("**Evidence.**")
    for e in h.evidence:
        lines.append(f"- *({e.kind})* {e.statement}  ")
        lines.append(f"  ↳ source: `{e.source.dataset}` — {e.source.locator}")
        if e.temporal_caveat:
            lines.append(f"  ⚠ **temporal caveat:** {e.temporal_caveat}")
    lines.append("")
    lines.append("**Assumptions.**")
    for a in h.assumptions:
        lines.append(f"- {a}")
    lines.append("")
    lines.append("**Counter-considerations.**")
    for cc in h.counter_considerations:
        lines.append(f"- {cc}")
    lines.append("")
    lines.append(f"**Falsification.** {h.falsification}")
    lines.append("")
    return "\n".join(lines)


def render_markdown(hs: HypothesisSet) -> str:
    lines: list[str] = []
    lines.append(f"# Source-attribution hypotheses — {hs.phenomenon}")
    lines.append("")
    lines.append(
        f"Event: `{hs.event_id}` · generated by `{hs.generated_method}` "
        f"(deterministic, templated — no LLM)."
    )
    lines.append("")
    lines.append("## Headline finding")
    lines.append("")
    lines.append(f"> {hs.headline_finding}")
    lines.append("")
    lines.append(f"**Confidence cap.** {hs.confidence_cap}")
    lines.append("")
    lines.append(f"**Scoring disclaimer.** {hs.scoring_disclaimer}")
    lines.append("")
    lines.append("## Plume summary (from committed Stage A/B outputs)")
    lines.append("")
    for k, v in hs.plume_summary.items():
        lines.append(f"- {k}: {v}")
    lines.append("")
    lines.append("## Ranked hypotheses")
    lines.append("")
    for h in hs.hypotheses:
        lines.append(_hypothesis_md(h))
    lines.append("## Global assumptions (apply to all hypotheses)")
    lines.append("")
    for a in hs.global_assumptions:
        lines.append(f"- {a}")
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    for k, v in hs.provenance.items():
        lines.append(f"- {k}: `{v}`")
    lines.append("")
    return "\n".join(lines)
