"""Locked, source-cited constants for the Sprint 2 methane detection pipeline.

Every numeric or string choice in this file has a primary source. Do not tune
any of these to make our flux match NASA's 18.3 t/hr — see the anti-fabrication
rule in docs/tasks/sprint2_detection_quantification.md.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# Sprint 2 canonical event — Turkmenistan Goturdepe, EMIT 2022-08-15 04:28:38 UTC
# --------------------------------------------------------------------------- #
# Verified via CMR direct query: the 20220815T042838 granule footprint is
# lon 53.29 to 54.64, lat 38.86 to 40.12 — Goturdepe / Barsagelmez oil &
# gas fields in Turkmenistan, NOT Carlsbad NM. The NASA per-granule unit
# absorption spectrum file shipped in EMIT-Data-Resources
# (data/methane_tutorial/emit20220815t042838_ch4_target) was generated for
# THIS granule and is valid only for this granule. Sprint 2 Stage A runs on
# this overpass; Thorpe 2023 publishes a peer-reviewed 163 +/- 18 t/hr
# cluster total across the multi-source Goturdepe + Barsagelmez fields for
# this imaging date. See eval/benchmark/turkmenistan_goturdepe_2022_08_15.yaml.
#
# Sources:
# - NASA EMIT-Data-Resources tutorial Generating_Methane_Spectral_Fingerprint.ipynb
#   https://github.com/nasa/EMIT-Data-Resources
# - Thorpe et al. 2023, Sci. Adv. 9 eadh2391, doi:10.1126/sciadv.adh2391
# - CMR query (run live): cmr.earthdata.nasa.gov/search/granules.umm_json
TURKMENISTAN_GOTURDEPE_2022_08_15_ACQUISITION_UTC = "2022-08-15T04:28:38Z"
TURKMENISTAN_GOTURDEPE_2022_08_15_L1B_GRANULE_UR = (
    "EMIT_L1B_RAD_001_20220815T042838_2222703_003"
)
TURKMENISTAN_GOTURDEPE_2022_08_15_L2A_MASK_GRANULE_UR = (
    "EMIT_L2A_MASK_002_20220815T042838_2222703_003"
)
TURKMENISTAN_GOTURDEPE_2022_08_15_L2B_CH4_GRANULE_UR = (
    "EMIT_L2B_CH4ENH_002_20220815T042838_2222703_003"
)

# NASA's per-granule target spectrum file. Plain-text, fetchable via:
#   curl -fLo <path> https://raw.githubusercontent.com/.../<TARGET_FILENAME>
# 285 rows of "index  wavelength_nm  value" matching EMIT's 285 native bands.
# The values carry their intrinsic negative sign for absorbing bands.
TURKMENISTAN_GOTURDEPE_2022_08_15_TARGET_FILENAME = "emit20220815t042838_ch4_target"
TURKMENISTAN_GOTURDEPE_2022_08_15_TARGET_URL = (
    "https://raw.githubusercontent.com/nasa/EMIT-Data-Resources/main/"
    "data/methane_tutorial/emit20220815t042838_ch4_target"
)


# --------------------------------------------------------------------------- #
# Permian (Carlsbad NM) plume - DEFERRED in Sprint 2
# --------------------------------------------------------------------------- #
# CMR confirms NASA's L2B plume complex catalogue covers the Carlsbad bbox
# only on 2022-08-26 and 2023-02-05 in 2022-23. The Aug 26 granule is the
# canonical Permian overpass for the iconic NASA October 2022 announcement
# (the Sept 13 - Jan 6 EMIT power outage rules out Sept/Oct 2022 acquisitions).
# NASA's 18.3 t/hr figure is a press release value with no peer-reviewed
# citation and no NASA-published per-granule unit absorption spectrum exists
# for this overpass. Sprint 2 does NOT process this granule. Sprint 3+ will,
# after we generate a HITRAN-based k.
PERMIAN_2022_08_26_ACQUISITION_UTC = "2022-08-26T17:46:42Z"
PERMIAN_2022_08_26_L1B_GRANULE_UR = (
    "EMIT_L1B_RAD_001_20220826T174642_2223812_024"
)
PERMIAN_2022_08_26_L2A_MASK_GRANULE_UR = (
    "EMIT_L2A_MASK_002_20220826T174642_2223812_024"
)
PERMIAN_2022_08_26_L2B_CH4_GRANULE_UR = (
    "EMIT_L2B_CH4ENH_002_20220826T174642_2223812_024"
)


# --------------------------------------------------------------------------- #
# Matched-filter output unit conversion
# --------------------------------------------------------------------------- #
# NASA's per-granule unit absorption spectrum was generated by MODTRAN with a
# specific Δc perturbation (the published EMIT target file numerically encodes
# k * Δc rather than k itself). The matched filter's raw α is therefore in
# units of Δc, not ppm·m. The conversion factor is published as the
# `--ppm_scaling` flag in NASA's operational matched filter, with default value
# 100000.0. Multiplying the raw MF output by this constant yields ppm·m.
#
# IMPORTANT: this constant is specific to NASA's per-granule target file
# generated for granule 20220815T042838 (and other EMIT-Data-Resources
# targets that share its MODTRAN Δc convention). If we ever generate k
# ourselves from HITRAN cross-sections (Sprint 3+ scope), this constant
# must be re-derived from our own Δc choice — likely 1.0 if we calibrate
# k directly in 1/(ppm·m).
#
# Source: NASA emit-sds/emit-ghg/parallel_mf.py:
#   parser.add_argument('--ppm_scaling', type=float, default=100000.0,
#                       help='scaling factor to unit convert outputs - based on target')
#   ...
#   mf[col, no_radiance_mask] = mf_col * args.ppm_scaling
MF_PPM_SCALING_FACTOR: float = 100000.0


# --------------------------------------------------------------------------- #
# Matched-filter spectral windows — narrow CH4 window
# --------------------------------------------------------------------------- #
# We use the narrow SWIR methane window 2137-2493 nm as the active band set
# for the matched filter. This is the gas-specific default in NASA's inner
# matched-filter routine `parallel_mf.py`:
#
#   if 'ch4' in args.library:
#       args.wavelength_range = [2137, 2493]
#
# *Why not the 3-window union (500-1340, 1500-1790, 1950-2450 nm)?*
# That broader set is the default in the higher-level NASA wrapper
# `ghg_process.py`, which is documented in EMIT GHG ATBD v0.2 §4.2.3. The
# broader set keeps ~219 EMIT bands; with only ~1280 column samples to
# estimate a 219x219 covariance, the inverse is highly underdetermined and
# the matched filter produces spurious bright artifacts unless stabilised by
# Monte Carlo bagging (NASA: --n_mc=10, --mc_bag_fraction=0.7) and dominant
# principal-component removal (--remove_dominant_pcs). Reproducing that
# stabilisation machinery is out of Sprint 2 scope.
#
# The narrow CH4 window (~49 EMIT bands) gives a well-conditioned 49x49
# covariance from the same 1280 samples, achieves correct output magnitudes
# without bagging, and is what the inner NASA matched-filter routine itself
# defaults to when invoked directly. It contains the entire SWIR methane
# absorption complex (the 2-nu3 band at 2.3 μm and shoulders).
#
# Sources:
# - EMIT-SDS operational code: github.com/emit-sds/emit-ghg, parallel_mf.py:
#     if 'ch4' in args.library: args.wavelength_range = [2137, 2493]
# - EMIT GHG ATBD v0.2 (Apr 2025), §4.2.3 (JPL D-107866) — describes the
#   3-window union used by the ghg_process.py wrapper with bagging.
MF_SPECTRAL_WINDOWS_NM: tuple[tuple[float, float], ...] = (
    (2137.0, 2493.0),
)


# --------------------------------------------------------------------------- #
# Covariance shrinkage — fixed diagonal-loading α (default)
# --------------------------------------------------------------------------- #
# Every per-column covariance is regularised by diagonal-loading shrinkage:
#     C_shrunk = (1 - α) S + α diag(S),       S = empirical sample covariance.
# We use a fixed α = 1e-9 per the EMIT GHG ATBD §4.2.1 ("a simple shrinkage
# method ... with a = 1e-9"). This gives the validated Stage A configuration:
# bbox Pearson ≈ 0.75 against NASA's L2B CH4ENH for the Goturdepe granule.
#
# **LOOCV-fit shrinkage is available behind an opt-in but is NOT the default.**
# NASA's operational `parallel_mf.py` uses LOOCV (Theiler 2012 closed form);
# we ported it verbatim (bit-identical alpha selection vs NASA's
# implementation on real EMIT columns — see scripts/diagnose_loocv_centering.py).
# When applied to uncentered EMIT radiance — which is how NASA's flow calls
# the function — LOOCV picks a median α ≈ 3e-4 with a mean-Mahalanobis bias
# that:
#   1. degrades the bulk-scene Pearson (0.75 → 0.64 measured)
#   2. does NOT preferentially regularise the blob-producing columns
#      (blob columns get α below the bulk median)
#   3. does NOT remove the round-blob artefacts at all (+2-8% blob mass)
# To opt in for an experiment, pass ``shrinkage_alpha="loocv"`` to
# ``run_matched_filter``. The function :func:`fit_looshrinkage_alpha` remains
# importable for diagnostic use.
#
# Sources:
# - EMIT GHG ATBD v0.2 §4.2.1 (JPL D-107866): a fixed α = 1e-9.
# - NASA emit-sds/emit-ghg/parallel_mf.py::fit_looshrinkage_alpha (LOOCV;
#   our port lives in matched_filter.py for diagnostic use only).
# - Theiler, "The Incredible Shrinking Covariance Estimator", Proc. SPIE,
#   2012, Eq. 29 — closed-form LOOCV objective.
MF_SHRINKAGE_ALPHA: float = 1e-9

# LOOCV grid + numerical-stability scaling — used only when the caller opts
# in via ``shrinkage_alpha="loocv"``.
MF_LOOCV_ALPHA_LOG10_MIN: float = -10.0
MF_LOOCV_ALPHA_LOG10_MAX: float = 0.0
MF_LOOCV_ALPHA_LOG10_STEP: float = 0.05
MF_LOOCV_STABILITY_SCALING: float = 100.0


# --------------------------------------------------------------------------- #
# Flare / hot-pixel exclusion band
# --------------------------------------------------------------------------- #
# EMIT excludes very bright pixels at ~2389 nm from the background statistics
# to prevent thermal emitters (flares) inflating Σ and faking absorption.
# The threshold corresponds to MODTRAN nadir radiance under no atmospheric H2O
# or CH4 with 80% surface reflectivity. We do not have access to that scene's
# MODTRAN run; we detect the band by wavelength instead of by fixed index.
# Source: EMIT GHG ATBD v0.2 §4.2.1.
FLARE_DETECTION_WAVELENGTH_NM: float = 2389.0


# --------------------------------------------------------------------------- #
# Varon et al. 2018 IME / U_eff parameterization
# --------------------------------------------------------------------------- #
# Effective wind speed for the IME emission rate:
#     U_eff = ALPHA_1 * ln(U10) + ALPHA_2     [m/s, natural log]
# Coefficients are from Varon et al. 2018, AMT 11, 5673-5686, Eq. (12) Fig. 4.
# ALPHA_1 is reported as 0.9-1.1 across 1%-5% instrument precision; we take the
# midpoint as a single value with the spread propagated as uncertainty. ALPHA_2
# is a fixed 0.6 m/s in the published fit. The parameterization was derived
# from WRF-LES of GHGSat-class (50x50 m, 1-5% precision) observations and
# applied here to EMIT (60x60 m); this transfer is the dominant model-form
# uncertainty in our flux estimate. NEVER tune these to NASA's 18.3 t/hr.
#
# Source: Varon et al. 2018, doi:10.5194/amt-11-5673-2018 (Eq. 12).
VARON2018_ALPHA_1: float = 1.0
VARON2018_ALPHA_1_UNCERTAINTY: float = 0.1  # half-range of 0.9-1.1
VARON2018_ALPHA_2: float = 0.6  # m/s
VARON2018_U10_MIN_VALID_MS: float = 2.0  # below this, parameterization degrades


# --------------------------------------------------------------------------- #
# Methane / air physical constants
# --------------------------------------------------------------------------- #
# CODATA / NIST. Conversions from MF output (ppm·m) to mass column (kg/m²) use
# n_air = p / (R * T) with surface p, T from ERA5 at the source pixel.
M_CH4_KG_PER_MOL: float = 0.01604      # CODATA methane molar mass
M_AIR_KG_PER_MOL: float = 0.02897      # standard dry-air molar mass
R_UNIVERSAL_J_PER_MOL_K: float = 8.314462618  # CODATA
